find_package(Git QUIET)

set(_hash "unknown")
set(_branch "unknown")
set(_date "unknown")
set(_dirty "")

if(GIT_FOUND AND EXISTS "${SRC_DIR}/.git")
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _hash
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _branch
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    # commit date, not "now": keeps the build reproducible
    execute_process(COMMAND "${GIT_EXECUTABLE}" log -1 --format=%cs
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _date
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${SRC_DIR}" OUTPUT_VARIABLE _status
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT _status STREQUAL "")
        set(_dirty "+dirty")
    endif()
endif()

set(_content "// Generated by cmake/GenerateBuildInfo.cmake - do not edit.
#pragma once

#define OPENTM_VERSION \"${OPENTM_VERSION}\"
#define OPENTM_GIT_HASH \"${_hash}${_dirty}\"
#define OPENTM_GIT_BRANCH \"${_branch}\"
#define OPENTM_COMMIT_DATE \"${_date}\"
#define OPENTM_BUILD_TYPE \"${BUILD_TYPE}\"
#define OPENTM_COMPILER \"${CXX_COMPILER} ${CXX_COMPILER_VERSION}\"
")

set(_existing "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _existing)
endif()
if(NOT _existing STREQUAL _content)
    file(WRITE "${OUT_FILE}" "${_content}")
endif()
